USE SoftUni

CREATE TABLE Towns 
(Id INT PRIMARY KEY IDENTITY (1,1),
Name NVARCHAR (50) NOT NULL)

CREATE TABLE Addresses
(Id INT PRIMARY KEY IDENTITY (1,1),
AddressText NVARCHAR (50) NOT NULL,
TownId INT FOREIGN KEY(TownId) REFERENCES Towns(Id) NOT NULL)

CREATE TABLE Departments  
(Id INT PRIMARY KEY IDENTITY (1,1),
Name NVARCHAR (50) NOT NULL)

CREATE TABLE Employees
(Id INT PRIMARY KEY IDENTITY (1,1),
FirstName NVARCHAR(50) NOT NULL,
MiddleName NVARCHAR(50),
LastName NVARCHAR(50) NOT NULL,
JobTitle NVARCHAR(50),
DepartmentId INT FOREIGN KEY(DepartmentId) REFERENCES Departments(Id),
HireDate DATE,
Salary DEC,
AddressId INT FOREIGN KEY(AddressId) REFERENCES Addresses(Id))



SELECT * FROM Towns
SELECT * FROM Departments 
SELECT * FROM Employees